name: Compile TypeScript in front

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Validate
        run: |
          cd front
          yarn validate
